services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: stock-mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123!
    ports:
      - "1433:1433"
    restart: always

  backend:
    build:
      context: ./backend-stock
      dockerfile: Dockerfile
    container_name: stock-backend
    depends_on: [mssql]
    environment:
      - DATABASE_URL=sqlserver://sa:Password123!@mssql:1433?database=gestion_stock&encrypt=true&trustServerCertificate=true
    ports:
      - "3000:3000"
    command: >
      sh -c "npx prisma generate &&
             npx prisma migrate deploy &&
             npm run start:prod"


  frontend:
    build:
      context: ./frontend-stock
    container_name: stock-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mssql_data:
