services:
  backend:
    build:
      context: ./backend-stock
      dockerfile: Dockerfile
    container_name: stock-backend
    environment:
      - DATABASE_URL=mysql://root@host.docker.internal:3306/gestion_stock
      - NODE_ENV=production
      - JWT_SECRET=change_this_secret_in_production
      - JWT_EXPIRES=7d
    ports:
      - "4000:3000"
    restart: unless-stopped
    command: >
      bash -lc "
        sleep 10 &&
        npx prisma generate &&
        npx prisma db push &&
        npm run build &&
        npm run start:prod
      "

  frontend:
    build:
      context: ./frontend-stock
      dockerfile: Dockerfile.prod
    container_name: stock-frontend
    depends_on:
      - backend
    ports:
      - "8088:80"
    restart: unless-stopped