server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /auth/ {
    proxy_pass http://backend:3000/auth/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /machines {
    proxy_pass http://backend:3000/machines;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /destinations {
    proxy_pass http://backend:3000/destinations;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /history {
    proxy_pass http://backend:3000/history;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /init {
    proxy_pass http://backend:3000/init;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}